language: node_js
sudo: false
node_js:
  - 12
  - 14
os:
  - linux
  - osx
addons:
    firefox: latest
    chrome: stable
install:
  - yarn install
  - lerna run build
script:
    - yarn test -- --verbose
cache: yarn
